services:
  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: unless-stopped
    working_dir: /app
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./:/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  php-fpm:
    build: docker/php-fpm
    container_name: php-fpm
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./:/app
  php-cli:
    build: docker/php-cli
    container_name: php-cli
    working_dir: /app
    tty: true
    volumes:
      - ./:/app
  db:
    image: 'mysql:8'
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - '${DB_PUBLIC_PORT}:3306'
    volumes:
      - ./docker/storage/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
  node:
    build: docker/node
    container_name: node
    working_dir: /app
    tty: true
    volumes:
      - ./:/app
